platform :ios, '7.0' 
target ‘testRongPay’ do
pod 'AFNetworking', '~> 3.1.0’
pod 'FrameAccessor'
pod 'ReactiveCocoa'
pod 'IQKeyboardManager'
pod 'YYModel'
pod 'FCUUID'
pod 'SVProgressHUD'
pod 'Masonry'

end
